import React from 'react';
import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import Header from "@/components/Header";
import QueryClientProviderWrapper from "@/components/QueryClientProviderWrapper";

const sans = Open_Sans({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Todo Calendar',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={sans.className}>
      <body>
        <div className="container">
          <Header/>
          <QueryClientProviderWrapper>
            {children}
          </QueryClientProviderWrapper>
        </div>
     </body>
    </html>
  )
}
