import React from 'react';
import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'

const sans = Open_Sans({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Todo Calendar',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={sans.className}>
      <body className="font-normal leading-relaxed text-[var(--color-gray-dark-2)] bg-gradient-to-br from-[var(--color-teritary-light)] to-[var(--color-teritary-dark)] bg-cover bg-no-repeat min-h-screen" >{children}</body>
    </html>
  )
}
